version: '3.12'

services:
  postgresql:
    container_name: postgresql
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=telegram
    ports:
      - "5432:5432"
    volumes:
      - ./db/:/var/lib/postgresql/data
    hostname: "database"

